version: "3"

services:

{{#boundedContexts}}
  generate-{{name}}:
    tty: true
    env_file:
      - .env
    image: ghcr.io/jinyoung/gpt-engineer:v1
    volumes:
      - ../{{name}}:/project
{{/boundedContexts}}